# Generated by Django 3.2.3 on 2021-05-25 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='date_joined',
            field=models.DateField(default='1111-11-11'),
        ),
        migrations.AddField(
            model_name='person',
            name='date_updated',
            field=models.DateField(default='1111-11-11'),
        ),
    ]
