# Generated by Django 3.2.3 on 2021-05-27 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person_api', '0003_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='person',
        ),
        migrations.AddField(
            model_name='person',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='person_api.job'),
        ),
    ]
